service: tydzien07-rest-dynamodb

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1

functions:
  hello:
    handler: src/function.hello