service: tydzien07-rest-dynamodb

plugins:
  - serverless-offline

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1

functions:
  getAll:
    handler: src/function.getAll
    events:
      - http:
          path: products
          method: GET
        
  create:
    handler: src/function.create
    events:
      - http:
          path: products
          method: POST