@host = https://vigsya55zl.execute-api.eu-central-1.amazonaws.com/dev

####
# getAll
GET {{host}}/products

####
# create
POST {{host}}/products
Content-Type: application/json

{
    "name": "wiadro",
    "description": "Można w nim trzymać wodę lub pliki"
}

####
# getById
GET {{host}}/products/1

####
# update
PUT {{host}}/products/1
Content-Type: application/json

{
    "name": "nowe wiadro",
    "description": "nowy opis Można w nim trzymać wodę lub pliki"
}

####
# delete
DELETE {{host}}/products/1